# Mapping nama tampilan ke kategori internal
MODEL_MAP = {
    "Bottle": "bottle",
    "Cable": "cable",
    "Capsule": "capsule",
    "Carpet": "carpet",
    "Grid": "grid",
    "Hazelnut": "hazelnut",
    "Leather": "leather",
    "Metal": "metal_nut",
    "Pill": "pill",
    "Screw": "screw",
    "Tile": "tile",
    "Toothbrush": "toothbrush",
    "Transistor": "transistor",
    "Wood": "wood",
    "Zipper": "zipper"
}
COMPLEX_CATEGORIES = {
    "Breakfast Box": "breakfast_box",
    "Juice Bottle": "juice_bottle",
    "Pushpins": "pushpins",
    "Screw Bag": "screw_bag",
    "Splicing Connectors": "splicing_connectors",
}

# threshold configurations for different models
thresholds_CSAD = {
    "breakfast_box": {"logical": 2.3232, "structural": -1.4716},
    "juice_bottle": {"logical": 13.4014, "structural": 14.5729},
    "pushpins": {"logical": 8.9723, "structural": 3.4282},
    "screw_bag": {"logical": 9.4575, "structural": 4.5171},
    "splicing_connectors": {"logical": 12.4772, "structural": 12.2652},
}
thresholds_GLASS = {
    "bottle": 0.9495,
    "cable": 0.6089,
    "capsule": 0.6297,
    "carpet": 0.9357,
    "grid": 0.7292,
    "hazelnut": 0.9702,
    "leather": 0.9311,
    "metal_nut": 0.7905,
    "pill": 0.3974,
    "screw": 0.4773,
    "tile": 0.9774,
    "toothbrush": 0.9055,
    "transistor":0.9818,
    "wood": 0.9737,
    "zipper": 0.8219,
}
### thresholds model ini belum di inisiasi
thresholds_Autoencoder = {
    "bottle": 0,
    "cable": 0,
    "capsule": 0,
    "carpet": 0,
    "grid": 0,
    "hazelnut": 0,
    "leather": 0,
    "metal_nut": 0,
    "pill": 0,
    "screw": 0,
    "tile": 0,
    "toothbrush": 0,
    "transistor":0,
    "wood": 0,
    "zipper": 0,
}
thresholds_ResNet50 = {
    "bottle": 0,
    "cable": 0,
    "capsule": 0,
    "carpet": 0,
    "grid": 0,
    "hazelnut": 0,
    "leather": 0,
    "metal_nut": 0,
    "pill": 0,
    "screw": 0,
    "tile": 0,
    "toothbrush": 0,
    "transistor":0,
    "wood": 0,
    "zipper": 0,
}
thresholds_Res2Net = {
    "bottle": 0,
    "cable": 0,
    "capsule": 0,
    "carpet": 0,
    "grid": 0,
    "hazelnut": 0,
    "leather": 0,
    "metal_nut": 0,
    "pill": 0,
    "screw": 0,
    "tile": 0,
    "toothbrush": 0,
    "transistor":0,
    "wood": 0,
    "zipper": 0,
}
thresholds_PatchCore = {
    "bottle": 0,
    "cable": 0,
    "capsule": 0,
    "carpet": 0,
    "grid": 0,
    "hazelnut": 0,
    "leather": 0,
    "metal_nut": 0,
    "pill": 0,
    "screw": 0,
    "tile": 0,
    "toothbrush": 0,
    "transistor":0,
    "wood": 0,
    "zipper": 0,
}
# accuracy configurations
accuracy_GLASS = {
    "overall": 99,
    "bottle": 100,
    "cable": 98,
    "capsule": 99,
    "carpet": 98,
    "grid": 100,
    "hazelnut": 100,
    "leather": 100,
    "metal_nut": 100,
    "pill": 97,
    "screw": 99,
    "tile": 100,
    "toothbrush": 100,
    "transistor":99,
    "wood": 98,
    "zipper": 99,
}
accuracy_CSAD = {
    "overall": 91,
    "breakfast_box": 89,
    "juice_bottle": 92,
    "pushpins": 93,
    "screw_bag": 94,
    "splicing_connectors": 91,
}
### accuracy belum di inisiasi
accuracy_Autoencoder = {
    "overall": 0,
    "bottle": 0,
    "cable": 0,
    "capsule": 0,
    "carpet": 0,
    "grid": 0,
    "hazelnut": 0,
    "leather": 0,
    "metal_nut": 0,
    "pill": 0,
    "screw": 0,
    "tile": 0,
    "toothbrush": 0,
    "transistor":0,
    "wood": 0,
    "zipper": 0,
}
accuracy_ResNet50 = {
    "overall": 0,
    "bottle": 0,
    "cable": 0,
    "capsule": 0,
    "carpet": 0,
    "grid": 0,
    "hazelnut": 0,
    "leather": 0,
    "metal_nut": 0,
    "pill": 0,
    "screw": 0,
    "tile": 0,
    "toothbrush": 0,
    "transistor":0,
    "wood": 0,
    "zipper": 0,
}
accuracy_Res2Net = {
    "overall": 0,
    "bottle": 0,
    "cable": 0,
    "capsule": 0,
    "carpet": 0,
    "grid": 0,
    "hazelnut": 0,
    "leather": 0,
    "metal_nut": 0,
    "pill": 0,
    "screw": 0,
    "tile": 0,
    "toothbrush": 0,
    "transistor":0,
    "wood": 0,
    "zipper": 0,
}
accuracy_PatchCore = {
    "overall": 0,
    "bottle": 0,
    "cable": 0,
    "capsule": 0,
    "carpet": 0,
    "grid": 0,
    "hazelnut": 0,
    "leather": 0,
    "metal_nut": 0,
    "pill": 0,
    "screw": 0,
    "tile": 0,
    "toothbrush": 0,
    "transistor":0,
    "wood": 0,
    "zipper": 0,
}